# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/monicag/example-container-app/app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: sha-311f1c4
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
service:
  type: LoadBalancer
  port: 6000
  targetPort: 5050
extraEnv:
  app_word: December
