apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-container-app-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: {{ .Values.service.targetPort }}
        env:
          - name: APP_PORT
            value: {{ .Values.service.targetPort }}
