apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-patch-deployment
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.28.2
          command:
            - /bin/sh
            - -c
            - kubectl patch deployment example-container-app-deployment -n mlg --type merge --patch '{{ .Files.Get "patches/deployment-patch.yaml" }}'
      restartPolicy: OnFailure
