apiVersion: v1
kind: Service
metadata:
  name: example-container-app-service
spec:
  selector:
    app: test-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}