apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-container-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        imagePullPolicy: Always
        image: ghcr.io/monicag/example-container-app/app:sha-14bd3b1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
