name: Stuff to do when branch is deleted

on:
  pull_request:
    types: ["closed", "unlabeled"]
  delete:

jobs:

  should-run:
    runs-on: ubuntu-latest
    outputs:
      SHOULD_RUN: ${{ steps.should_run.outputs.SHOULD_RUN }}
    steps:
      - name: Check if this workflow should run
        id: should_run
        run: |
          should_run=false
          if ${{ contains(github.event.pull_request.labels.*.name, 'preview') || ( github.event_name == 'delete' &&  contains(github.event.ref, 'example-container-app-pr-')) }} ; then
            should_run=true
          fi
          echo "SHOULD_RUN=$should_run" >> "$GITHUB_OUTPUT"
  
  get-app-name:
    needs: should-run
    if: needs.should-run.outputs.SHOULD_RUN == 'true'
    uses: ./.github/workflows/get-app-name.yaml
  
  stuff-job:
    
    needs: [get-app-name, should-run]
    if: needs.should-run.outputs.SHOULD_RUN == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: What branch
        run: |
          echo "what is this"
          echo ${{ github.event.ref }}
          echo "app name is ${{ needs.get-app-name.outputs.APP_NAME }}"

